### ISSUE TITLE
How to run this server

### ISSUE THREAD

**Issue by bajki** [arpitjindal97/barcode-server#1]
Hi, can you please help mi to run this server on arch linux.

Thanks

**Comment by arpitjindal97** [comment]
I made this project for my personal use but I am glad that you want to use it. I have uploaded a built for Linux. Check [this](https://github.com/arpitjindal97/barcode-server/releases) URL.

Execute this binary and Click on Start. Server will be up and running. Visit `localhost:8080/status` to know if it is running. 

The client which will scan the barcode will need to make a POST request to `server_ip:8080/result` with body containing JSON in the given format:

`{"result":"this is scan result"}`

I will be adding proper README file soon. Feel free to ask any question if you have any problem.

**Comment by bajki** [comment]
My port 8080 is used so i can't use it..

Can you provide how can i change port and build binary..

Im new to go

Thanks

**Comment by arpitjindal97** [comment]
Go to this line and change the port

https://github.com/arpitjindal97/barcode-server/blob/master/Server.go#L31

Compilation steps

- `sudo pacman -S go`
- `go get -u -v github.com/therecipe/qt/cmd/...`
- `sudo pacman -S docker`
- `docker pull therecipe/qt:linux` // this is gonna take long time and data
- `GOPATH="/home/user/go"` // replace it with your username
- `PATH="$PATH:$GOPATH/bin/"`
- `cd $GOPATH/src`
- `mkdir -p github.com/arpitjindal97`
- `cd github.com/arpitjindal97`
- `git clone https://github.com/arpitjindal97/barcode-server`
- `cd barcode-server`
- `qtdeploy -docker build linux`
- `./deploy/linux/barcode-server`
